# Generated by Django 4.0.3 on 2022-05-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
