# Generated by Django 4.0.3 on 2022-05-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name': 'Task', 'verbose_name_plural': 'Задачи'},
        ),
    ]
