# Generated by Django 4.0.3 on 2022-05-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
