# Generated by Django 4.0.3 on 2022-05-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
