# Generated by Django 4.0.3 on 2022-05-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_rename_creation_date_label_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['id'], 'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
    ]
